# Generated by Django 2.1.7 on 2019-03-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='portalItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal_praas.menuItem')),
            ],
            bases=('portal_praas.menuitem',),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='requiredPermissions',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Permission'),
        ),
    ]
