# Generated by Django 2.1.7 on 2019-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_praas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='requiresLogin',
            field=models.BooleanField(default=True),
        ),
    ]
