# Generated by Django 2.1.7 on 2019-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_praas', '0002_menuitem_requireslogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='onlyDisplayIfLoggedOut',
            field=models.BooleanField(default=False),
        ),
    ]
