# Generated by Django 2.1.7 on 2019-03-25 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_praas', '0003_menuitem_onlydisplayifloggedout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='requiredPermissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Permission'),
        ),
    ]
